// Generic (Markush) formulas: expanding them into compounds, reading alternatives from text,
// and what the editor asks about variables and sites. The model itself (what makes a
// variable, attachment or drawn piece valid) is core's and is re-exported here, so the
// rest of the app imports generic-formula code from this one place.
export * from "@structura/core/markush"
export { joiningSiteName } from "./choices.ts"
export { enumerate, enumerateSteps } from "./enumerate.ts"
export type { EnumerateOptions, Enumeration } from "./enumerate.ts"
export { formulasOf } from "./formulas.ts"
export { choiceText, pickFields } from "./picks.ts"
export type { Pick } from "./picks.ts"
export { compoundFields, enumerationFields, enumerationSdf } from "./export.ts"
export { librarySize } from "./count.ts"
export { repeatSkips } from "./repeats.ts"
export type { RepeatSkip } from "./repeats.ts"
export type { LibrarySize } from "./count.ts"
export { alternativesFromText } from "./parse.ts"
export { placeholders, shareSources, undefinedVariables, variableLabels } from "./queries.ts"
export { REPRESENTATIVES, representativesOf } from "./representatives.ts"
export { sameAlternative } from "./same.ts"
export { linkerNames, ringNames, siteKind } from "./sites.ts"
export type { SiteKind } from "./sites.ts"
export { fragmentAt, fragmentVersions } from "./fragments.ts"
export { builtinTemplates } from "./templates/index.ts"
export { libraryProblem, TEMPLATE_SITES, templateProblem } from "./templates/model.ts"
export type { ImportReport, Template, TemplateInput, TemplateLibrary, TemplateSite } from "./templates/model.ts"
