import { DOUBLE, HASH, SINGLE, TRIPLE, WEDGE } from "../constants.ts"
import type { AtomAction } from "./actions.ts"

/** The keys pressed over an atom. Upper case is Shift. */
export const ATOM_KEYS: Record<string, AtomAction> = {
  "1": { do: "extend", style: SINGLE },
  x: { do: "extend", style: SINGLE },
  "0": { do: "sprout-up" },
  "2": { do: "recipe", name: "carbonyl" },
  "8": { do: "extend", style: DOUBLE },
  z: { do: "extend", style: TRIPLE },
  "4": { do: "extend", style: WEDGE },
  "5": { do: "extend", style: HASH },
  "3": { do: "phenyl" },
  a: { do: "phenyl" },
  "6": { do: "ring", kind: "cyclohexane" },
  "7": { do: "ring", kind: "cyclopentane" },
  v: { do: "ring", kind: "cyclopropane" },
  u: { do: "ring", kind: "cyclobutane" },
  j: { do: "recipe", name: "chair" },
  J: { do: "recipe", name: "chair-flipped" },
  "9": { do: "recipe", name: "fork" },
  K: { do: "recipe", name: "tert-butyl", inChain: "stereo-pair" },
  k: { do: "recipe", name: "sulfonyl" },
  Z: { do: "recipe", name: "azide" },
  O: { do: "recipe", name: "methoxy" },
  N: { do: "recipe", name: "nitro" },
  F: { do: "recipe", name: "trifluoromethyl" },
  M: { do: "recipe", name: "magnesium-bromide" },
  o: { do: "become", el: "O" },
  q: { do: "become", el: "O" },
  n: { do: "become", el: "N" },
  w: { do: "become", el: "N" },
  s: { do: "become", el: "S" },
  S: { do: "become", el: "Si" },
  p: { do: "become", el: "P" },
  f: { do: "become", el: "F" },
  l: { do: "become", el: "Cl" },
  C: { do: "become", el: "Cl" },
  b: { do: "become", el: "Br" },
  i: { do: "become", el: "I" },
  h: { do: "become", el: "H" },
  L: { do: "become", el: "Li" },
  B: { do: "become", el: "B" },
  d: { do: "isotope", el: "H", isotope: 2 },
  m: { do: "label", text: "Me" },
  c: { do: "label", text: "CH3" },
  e: { do: "label", text: "Et" },
  P: { do: "label", text: "Ph" },
  A: { do: "label", text: "Ac" },
  E: { do: "label", text: "CO2Me" },
  H: { do: "label", text: "Cbz" },
  y: { do: "label", text: "Boc" },
  Q: { do: "label", text: "Fmoc" },
  "+": { do: "charge", delta: 1 },
  "=": { do: "charge", delta: 1 },
  "-": { do: "charge", delta: -1 },
}
